# Generated by Django 5.2.1 on 2025-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartorderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='teachers',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='api.teacher'),
        ),
    ]
