# Generated by Django 5.2.1 on 2025-07-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cartorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='price',
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='api.course'),
        ),
    ]
